I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 249, in script
    $open1 += 1
  File "game/script.rpy", line 249, in <module>
    $open1 += 1
NameError: name 'open1' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 249, in script
    $open1 += 1
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 249, in <module>
    $open1 += 1
NameError: name 'open1' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.10.2178
Не смотри наверх. 1.0
Tue Feb  1 22:26:21 2022
